pipeline{
    agent any
    tools{
        maven 'Maven'
    }

    stages{
        stage('checkout'){
            steps{
                echo "================================[CHECKOUT]================================"
                git branch: 'main', url: 'https://github.com/Nonelela4980/jenkins-spring-app.git', credentialsId: '[REPLACE_WITH_CREDENTIALS_ID]'
            }
        }

        stage('TEST'){
            steps{
                echo "================================[CHECKOUT]================================"
                sh """
                    mvn verify --fail-never
                    mvn clean install
                    mvn test
                """
                }
        }
    }

   post {
        always {
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            junit 'target/surefire-reports/*.xml'
        }
    }
}